# Tasks required to have git-bz working for the vagrant user

- name: Clone Git-Bz
  git: repo={{ gitbz_repo }}  dest={{ gitbz_dir }} version={{ gitbz_version }}

- name: Make git-bz globally available
  file: src={{ gitbz_dir }}/git-bz dest=/usr/local/bin/git-bz state=link

- name: Git-Bz (permissions)
  file: path={{ gitbz_dir }} owner=vagrant group=vagrant recurse=yes state=directory
