# Tasks required to have Koha QA Tools working for the vagrant user
- name: Install Koha QA tools (dependencies)
  apt: pkg={{ item }} state=latest
  with_items:
    - libfile-chdir-perl
    - libgit-repository-perl
    - liblist-compare-perl
    - libmoo-perl
    - libperl-critic-perl
    - libtest-perl-critic-perl
    - libtest-perl-critic-progressive-perl
    - libsmart-comments-perl
    - libdatetimex-easy-perl
    - libtest-differences-perl
    - libdbd-sqlite2-perl
    - koha-perldeps

- name: Install Koha QA tools (not in wheezy)
  apt: pkg={{ item }} state=latest
  with_items:
    - codespell
  when: ansible_distribution_release != 'wheezy'

# Ignore this installation, because there has been added koha-perldeps
#- name: Install testing dependencies (cpanm)
#  become_user: root
#  cpanm: name={{ item }} mirror={{ cpan_mirror }}
#  with_items:
#    - HTTPD::Bench::ApacheBench
#    - Test::DBIx::Class
#
- name: Clone Koha QA tools
  git: repo={{ koha_qa_repo }}  dest={{ koha_qa_dir }} version={{ koha_qa_version }} accept_hostkey=yes

- name: Set perlcritic for the vagrant user
  file: src={{ koha_qa_dir }}/perlcriticrc dest={{ vagrant_home_dir }}/.perlcriticrc state=link

- name: Set perlcritic for the instance user
  file: src={{ koha_qa_dir }}/perlcriticrc dest=/var/lib/koha/{{ koha_instance_name }}/.perlcriticrc mode=0644 owner={{ koha_instance_name }}-koha state=link

- name: QA permissions
  file: path={{ koha_qa_dir }} owner=vagrant group=vagrant state=directory recurse=yes
