# Tasks required to have the release-tools working for the vagrant user
- name: Install deps
  apt: name={{ item }} state=latest
  with_items:
    - libhtml-tableextract-perl
    - libtext-multimarkdown-perl

- name: Install deps (cpan)
  cpanm: name={{ item }} mirror={{ cpan_mirror }}
  with_items:
    - File::FindLib
    - REST::Client

- name: Clone the release-tools repo
  git: repo={{ release_tools_repo }}  dest={{ release_tools_dir }} version={{ release_tools_version }}

- name: Clone the release-tools repo (permissions)
  file: path={{ release_tools_dir }} owner=vagrant group=vagrant recurse=yes state=directory
